Change clipboard manager

diff --git a/.local/share/bin/rofi/rofi-kill b/.local/share/bin/rofi/rofi-kill
--- a/.local/share/bin/rofi/rofi-kill
+++ b/.local/share/bin/rofi/rofi-kill
@@ -2,7 +2,7 @@
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -n "$1" ]; then
   cat <<EOF
-\$ dmenu_kill [FLAGS]
+\$ rofi-kill [FLAGS]
 Issue a kill command.
 
 Flags:
@@ -11,6 +11,6 @@ EOF
   exit 1
 fi
 
-command -v dmenu >/dev/null || { echo "error: dmenu is not installed, exiting..."; exit 1; }
+command -v rofi >/dev/null || { echo "error: rofi is not installed, exiting..."; exit 1; }
 
-killall `ps axch -o cmd | dmenu -p "kill:"`
+killall `ps axch -o cmd | rofi -dmenu -p "kill"`
diff --git a/.local/share/bin/rofi/rofi-power b/.local/share/bin/rofi/rofi-power
--- a/.local/share/bin/rofi/rofi-power
+++ b/.local/share/bin/rofi/rofi-power
@@ -2,7 +2,7 @@
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -n "$1" ]; then
   cat <<EOF
-\$ dmenu_power [FLAGS]
+\$ rofi-power [FLAGS]
 Issue a power command.
 
 Flags:
@@ -11,10 +11,10 @@ EOF
   exit 1
 fi
 
-command -v dmenu >/dev/null || { echo "error: dmenu is not installed, exiting..."; exit 1; }
+command -v rofi >/dev/null || { echo "error: rofi is not installed, exiting..."; exit 1; }
 command -v physlock >/dev/null || { echo "error: physlock is not installed, exiting..."; exit 1; }
 
-case `printf "reboot\nshutdown\nsuspend\nlock\nexit" | dmenu -c -l 5 -bw 3 -ww 300 -p "power:"` in
+case `printf "reboot\nshutdown\nsuspend\nlock\nexit" | rofi -dmenu -l 5 -p "power"` in
   "reboot")
     reboot;;
   "shutdown")
